package com.syntelinc.BOK.ATM.menupkg;
// Generated Apr 30, 2015 10:50:55 AM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Savingacct generated by hbm2java
 */
public class Savingacct  implements java.io.Serializable {


     private int accountid;
     private Userdetails userdetails;
     private Date createdate;
     private char status;

    public Savingacct() {
    }

    public Savingacct(int accountid, Userdetails userdetails, Date createdate, char status) {
       this.accountid = accountid;
       this.userdetails = userdetails;
       this.createdate = createdate;
       this.status = status;
    }
   
    public int getAccountid() {
        return this.accountid;
    }
    
    public void setAccountid(int accountid) {
        this.accountid = accountid;
    }
    public Userdetails getUserdetails() {
        return this.userdetails;
    }
    
    public void setUserdetails(Userdetails userdetails) {
        this.userdetails = userdetails;
    }
    public Date getCreatedate() {
        return this.createdate;
    }
    
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }
    public char getStatus() {
        return this.status;
    }
    
    public void setStatus(char status) {
        this.status = status;
    }




}


