package in.syntel.BOK.ATM.ministatement;
// Generated Apr 30, 2015 1:32:51 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Administratordetails generated by hbm2java
 */
public class Administratordetails  implements java.io.Serializable {


     private int adminid;
     private Branch branch;
     private int pinnum;
     private String name;
     private String phone;
     private String address;
     private String email;
     private String ssn;
     private Date dob;
     private Date doreg;
     private char status;

    public Administratordetails() {
    }

	
    public Administratordetails(int adminid, Branch branch, int pinnum, String name, String phone, String address, String ssn, Date dob, Date doreg, char status) {
        this.adminid = adminid;
        this.branch = branch;
        this.pinnum = pinnum;
        this.name = name;
        this.phone = phone;
        this.address = address;
        this.ssn = ssn;
        this.dob = dob;
        this.doreg = doreg;
        this.status = status;
    }
    public Administratordetails(int adminid, Branch branch, int pinnum, String name, String phone, String address, String email, String ssn, Date dob, Date doreg, char status) {
       this.adminid = adminid;
       this.branch = branch;
       this.pinnum = pinnum;
       this.name = name;
       this.phone = phone;
       this.address = address;
       this.email = email;
       this.ssn = ssn;
       this.dob = dob;
       this.doreg = doreg;
       this.status = status;
    }
   
    public int getAdminid() {
        return this.adminid;
    }
    
    public void setAdminid(int adminid) {
        this.adminid = adminid;
    }
    public Branch getBranch() {
        return this.branch;
    }
    
    public void setBranch(Branch branch) {
        this.branch = branch;
    }
    public int getPinnum() {
        return this.pinnum;
    }
    
    public void setPinnum(int pinnum) {
        this.pinnum = pinnum;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getSsn() {
        return this.ssn;
    }
    
    public void setSsn(String ssn) {
        this.ssn = ssn;
    }
    public Date getDob() {
        return this.dob;
    }
    
    public void setDob(Date dob) {
        this.dob = dob;
    }
    public Date getDoreg() {
        return this.doreg;
    }
    
    public void setDoreg(Date doreg) {
        this.doreg = doreg;
    }
    public char getStatus() {
        return this.status;
    }
    
    public void setStatus(char status) {
        this.status = status;
    }




}


