package in.syntel.BOK.ATM.ministatement;
// Generated Apr 30, 2015 1:32:51 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Branch generated by hbm2java
 */
public class Branch  implements java.io.Serializable {


     private int branchid;
     private int locationcode;
     private char status;
     private String address;
     private String phone;
     private Set administratordetailses = new HashSet(0);
     private Set atms = new HashSet(0);

    public Branch() {
    }

	
    public Branch(int branchid, int locationcode, char status, String address, String phone) {
        this.branchid = branchid;
        this.locationcode = locationcode;
        this.status = status;
        this.address = address;
        this.phone = phone;
    }
    public Branch(int branchid, int locationcode, char status, String address, String phone, Set administratordetailses, Set atms) {
       this.branchid = branchid;
       this.locationcode = locationcode;
       this.status = status;
       this.address = address;
       this.phone = phone;
       this.administratordetailses = administratordetailses;
       this.atms = atms;
    }
   
    public int getBranchid() {
        return this.branchid;
    }
    
    public void setBranchid(int branchid) {
        this.branchid = branchid;
    }
    public int getLocationcode() {
        return this.locationcode;
    }
    
    public void setLocationcode(int locationcode) {
        this.locationcode = locationcode;
    }
    public char getStatus() {
        return this.status;
    }
    
    public void setStatus(char status) {
        this.status = status;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public Set getAdministratordetailses() {
        return this.administratordetailses;
    }
    
    public void setAdministratordetailses(Set administratordetailses) {
        this.administratordetailses = administratordetailses;
    }
    public Set getAtms() {
        return this.atms;
    }
    
    public void setAtms(Set atms) {
        this.atms = atms;
    }




}


