package hibernate;
// Generated Apr 30, 2015 3:45:12 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Checkingacct generated by hbm2java
 */
public class Checkingacct  implements java.io.Serializable {


     private int checkingid;
     private Userdetails userdetails;
     private Date createdate;
     private char status;
     private Set checkingtranses = new HashSet(0);

    public Checkingacct() {
    }

	
    public Checkingacct(int checkingid, Userdetails userdetails, Date createdate, char status) {
        this.checkingid = checkingid;
        this.userdetails = userdetails;
        this.createdate = createdate;
        this.status = status;
    }
    public Checkingacct(int checkingid, Userdetails userdetails, Date createdate, char status, Set checkingtranses) {
       this.checkingid = checkingid;
       this.userdetails = userdetails;
       this.createdate = createdate;
       this.status = status;
       this.checkingtranses = checkingtranses;
    }
   
    public int getCheckingid() {
        return this.checkingid;
    }
    
    public void setCheckingid(int checkingid) {
        this.checkingid = checkingid;
    }
    public Userdetails getUserdetails() {
        return this.userdetails;
    }
    
    public void setUserdetails(Userdetails userdetails) {
        this.userdetails = userdetails;
    }
    public Date getCreatedate() {
        return this.createdate;
    }
    
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }
    public char getStatus() {
        return this.status;
    }
    
    public void setStatus(char status) {
        this.status = status;
    }
    public Set getCheckingtranses() {
        return this.checkingtranses;
    }
    
    public void setCheckingtranses(Set checkingtranses) {
        this.checkingtranses = checkingtranses;
    }




}


