package hibernate;
// Generated Apr 30, 2015 3:45:12 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Savingacct generated by hbm2java
 */
public class Savingacct  implements java.io.Serializable {


     private int savingid;
     private Userdetails userdetails;
     private Date createdate;
     private char status;
     private Set savingtranses = new HashSet(0);

    public Savingacct() {
    }

	
    public Savingacct(int savingid, Userdetails userdetails, Date createdate, char status) {
        this.savingid = savingid;
        this.userdetails = userdetails;
        this.createdate = createdate;
        this.status = status;
    }
    public Savingacct(int savingid, Userdetails userdetails, Date createdate, char status, Set savingtranses) {
       this.savingid = savingid;
       this.userdetails = userdetails;
       this.createdate = createdate;
       this.status = status;
       this.savingtranses = savingtranses;
    }
   
    public int getSavingid() {
        return this.savingid;
    }
    
    public void setSavingid(int savingid) {
        this.savingid = savingid;
    }
    public Userdetails getUserdetails() {
        return this.userdetails;
    }
    
    public void setUserdetails(Userdetails userdetails) {
        this.userdetails = userdetails;
    }
    public Date getCreatedate() {
        return this.createdate;
    }
    
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }
    public char getStatus() {
        return this.status;
    }
    
    public void setStatus(char status) {
        this.status = status;
    }
    public Set getSavingtranses() {
        return this.savingtranses;
    }
    
    public void setSavingtranses(Set savingtranses) {
        this.savingtranses = savingtranses;
    }




}


