package hibernate;
// Generated Apr 30, 2015 3:45:12 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Userdetails generated by hbm2java
 */
public class Userdetails  implements java.io.Serializable {


     private int userid;
     private int pinnum;
     private String name;
     private String phone;
     private String address;
     private String email;
     private String ssn;
     private Date dob;
     private Date doreg;
     private char status;
     private Set checkingaccts = new HashSet(0);
     private Set savingaccts = new HashSet(0);

    public Userdetails() {
    }

	
    public Userdetails(int userid, int pinnum, String name, String phone, String address, String ssn, Date dob, Date doreg, char status) {
        this.userid = userid;
        this.pinnum = pinnum;
        this.name = name;
        this.phone = phone;
        this.address = address;
        this.ssn = ssn;
        this.dob = dob;
        this.doreg = doreg;
        this.status = status;
    }
    public Userdetails(int userid, int pinnum, String name, String phone, String address, String email, String ssn, Date dob, Date doreg, char status, Set checkingaccts, Set savingaccts) {
       this.userid = userid;
       this.pinnum = pinnum;
       this.name = name;
       this.phone = phone;
       this.address = address;
       this.email = email;
       this.ssn = ssn;
       this.dob = dob;
       this.doreg = doreg;
       this.status = status;
       this.checkingaccts = checkingaccts;
       this.savingaccts = savingaccts;
    }
   
    public int getUserid() {
        return this.userid;
    }
    
    public void setUserid(int userid) {
        this.userid = userid;
    }
    public int getPinnum() {
        return this.pinnum;
    }
    
    public void setPinnum(int pinnum) {
        this.pinnum = pinnum;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getSsn() {
        return this.ssn;
    }
    
    public void setSsn(String ssn) {
        this.ssn = ssn;
    }
    public Date getDob() {
        return this.dob;
    }
    
    public void setDob(Date dob) {
        this.dob = dob;
    }
    public Date getDoreg() {
        return this.doreg;
    }
    
    public void setDoreg(Date doreg) {
        this.doreg = doreg;
    }
    public char getStatus() {
        return this.status;
    }
    
    public void setStatus(char status) {
        this.status = status;
    }
    public Set getCheckingaccts() {
        return this.checkingaccts;
    }
    
    public void setCheckingaccts(Set checkingaccts) {
        this.checkingaccts = checkingaccts;
    }
    public Set getSavingaccts() {
        return this.savingaccts;
    }
    
    public void setSavingaccts(Set savingaccts) {
        this.savingaccts = savingaccts;
    }




}


